version: '3.8'

services:

  wise-redis:
    image: redis

  wise-mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=iamroot
      - MYSQL_DATABASE=wise_database
      - MYSQL_USER=wiseuser
      - MYSQL_PASSWORD=wisepass
    volumes:
      - "${PWD}/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
      - "${PWD}/data:/var/lib/mysql"

  wise-api:
    image: wiseberkeley/wise-api-dev:v1
    depends_on:
      - wise-redis
      - wise-mysql
    ports:
      - "8080:8080"
    volumes:
      - "${PWD}/WISE-API:/app"

  wise-client:
    image: wiseberkeley/wise-client-dev:v1
    depends_on:
      - wise-api
    ports:
      - "4200:4200"
    volumes:
      - "${PWD}/WISE-Client:/app"

  wise-nginx:
    image: nginx:1.13
    depends_on:
      - wise-client
    ports:
      - "81:80"
    volumes:
      - "${PWD}/nginx/conf.d:/etc/nginx/conf.d"
